# Generated by Django 3.2.8 on 2021-12-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('adresa', models.CharField(max_length=50)),
                ('cijena', models.IntegerField(max_length=3)),
                ('max_gosti', models.IntegerField(max_length=2)),
                ('min_br_nocenja', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Gost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('prezime', models.CharField(max_length=50)),
                ('drzava', models.CharField(max_length=30)),
                ('grad', models.CharField(max_length=50)),
                ('oib', models.IntegerField(max_length=11)),
                ('datum_od', models.DateField()),
                ('datum_do', models.DateField()),
            ],
        ),
    ]
