# Generated by Django 3.2.8 on 2021-12-08 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartman',
            old_name='cijena',
            new_name='cijena_noci',
        ),
        migrations.RemoveField(
            model_name='gost',
            name='datum_do',
        ),
        migrations.RemoveField(
            model_name='gost',
            name='datum_od',
        ),
        migrations.CreateModel(
            name='Rezervacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_od', models.DateField()),
                ('datum_do', models.DateField()),
                ('broj_nocenja', models.IntegerField(max_length=2)),
                ('cijena_ukupno', models.IntegerField(max_length=5)),
                ('sifra_apartmana', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.apartman')),
                ('sifra_gosta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.gost')),
            ],
        ),
    ]
